
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.ListModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekhit borole
 */
public class jeemains extends javax.swing.JFrame {
 Connection c=null;
 Statement s=null;
 void con(){
 try{
        Class.forName("java.sql.Driver");
         c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
         s=c.createStatement();}catch(Exception e){System.out.println(e.getMessage());System.out.println(e.getMessage());}
 }
 void ti(){next.doClick();}
 int ans;
    int i=0;
    Timer t=new Timer((1000),new 
        ActionListener(){public void actionPerformed(ActionEvent e)
{
    
    int sec=Integer.parseInt(tt3.getText());int min=Integer.parseInt(tt2.getText()),hour=Integer.parseInt(tt1.getText());
    sec++;
    if(sec==60)
    {min++;sec=0;}
    if(min==60)
    {hour++;min=0;}
 

       tt1.setText(""+hour);tt2.setText(""+min);tt3.setText(""+sec);
        tt4.setText(hour+":"+min+":"+sec);
        //if(Integer.parseInt(tt3.getText())==5&& ans==5) 
//next.doClick();
        //next.doClick();
        System.out.println("ans in t="+ans);
       /* if((tt3.getText()).equals("5")&&ans!=9&&ans==5)
        try {
             test ob=new test();
       ResultSet rs1= ob.conn(database.getText(),tf2.getText(),"select","rans,ans","question="+cb1.getSelectedItem());
       rs1.absolute(1);
        if((rs1.getString("ans").equals("-1"))==false && rs1.getString("rans").equals(rs1.getString("ans"))==false)
next.doClick();rs1.close();
    } catch (Exception ee) {System.out.println("timer next "+ee.getMessage());
    }*/

}

});
    Timer t1=new Timer((1000),new 
        ActionListener(){public void actionPerformed(ActionEvent e)
{
    
    int sec=Integer.parseInt(tf6.getText());int min=Integer.parseInt(tf5.getText()),hour=Integer.parseInt(tf4.getText());
    sec++;//int min=0;int hour=0;
    if(sec==60)
    {min++;sec=0;}
 if(min==60)
 { hour++;min=0;}
         

      tf4.setText(""+hour);tf5.setText(""+min);tf6.setText(""+sec);
      //tt.setText(hour+":"+min+":"+sec);

}
});Timer t2=new Timer((1000),new 
        ActionListener(){public void actionPerformed(ActionEvent e)
{
    
    int sec=Integer.parseInt(tt7.getText());int min=Integer.parseInt(tt6.getText()),hour=Integer.parseInt(tt5.getText());
    sec++;//int min=0;int hour=0;
    if(sec==60)
    {min++;sec=0;}
 if(min==60)
 { hour++;min=0;}
         

      tt5.setText(""+hour);tt6.setText(""+min);tt7.setText(""+sec);
      //tt.setText(hour+":"+min+":"+sec);

}
});
    /**
     * Creates new form NewJFrame
     */
    public jeemains() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf2 = new javax.swing.JTextField();
        database = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();
        tt2 = new javax.swing.JTextField();
        tt3 = new javax.swing.JTextField();
        tt4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lt2 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lt3 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lt1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        check = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfa = new javax.swing.JTextField();
        ura = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        store = new javax.swing.JButton();
        cb2 = new javax.swing.JComboBox<>();
        plan1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lt4 = new javax.swing.JList<>();
        tt5 = new javax.swing.JTextField();
        tt6 = new javax.swing.JTextField();
        tt7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jb4 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(204, 255, 204));
        setIconImages(null);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf2.setText("bonding1l1");
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 32, 86, -1));

        database.setText("inorganic");
        database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseActionPerformed(evt);
            }
        });
        getContentPane().add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 61, 86, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 35, -1, -1));

        tt1.setText("00");
        getContentPane().add(tt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1278, 9, 38, 50));

        tt2.setText("00");
        getContentPane().add(tt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1328, 9, 38, 50));

        tt3.setText("00");
        getContentPane().add(tt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1388, 9, 38, 50));

        tt4.setText("jButton1");
        tt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tt4MouseExited(evt);
            }
        });
        tt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt4ActionPerformed(evt);
            }
        });
        getContentPane().add(tt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 0, 144, -1));

        lt2.setBorder(javax.swing.BorderFactory.createTitledBorder("reason for mistake"));
        lt2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.concept not known", "2.silly mistake", "3.mind blowing application of known concept", "4.must try more,may have got it", "5.paniced:not sure but answered", "6.confused with concepts", "7.#reagent unknown,new", "8.memory based,#reagent,#names", "9.tricked", "10.#noidea" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lt2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lt2FocusGained(evt);
            }
        });
        lt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lt2KeyPressed(evt);
            }
        });
        lt2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lt2ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lt2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 12, -1, -1));

        lt3.setBorder(javax.swing.BorderFactory.createTitledBorder("question type"));
        lt3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.good question,revision", "2.will get it:default", "3.to be avoided(lengthy)", "4.tricky:know the trick", "5.luck favoured #danger", "6.memory based,#reagent,#names", "7.#noidea", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lt3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lt3ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lt3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 0, -1, -1));

        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb1.setEditable(true);
        cb1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        cb1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb1PropertyChange(evt);
            }
        });
        cb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb1KeyPressed(evt);
            }
        });
        jPanel3.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 13, 80, 64));

        lt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lt1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "a", "b", "c", "d", "e" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lt1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lt1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lt1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 84, 106, 178));

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 324, 75, 70));

        jButton2.setMnemonic('a');
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 249, 75, 68));

        next.setMnemonic('d');
        next.setText("d next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel3.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 75, 74));

        check.setMnemonic('s');
        check.setText("s check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel3.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 171, -1, 65));

        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 16, -1, -1));

        tfa.setText("                ");
        jPanel3.add(tfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 13, -1, -1));

        ura.setText("jTextField1");
        jPanel3.add(ura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 50, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        tf6.setText("00");
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1798, 29, 30, 40));

        tf5.setText("00");
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1758, 29, 30, 40));

        tf4.setText("00");
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1718, 29, 30, 40));

        jLabel3.setText("chapter time keeper");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2496, 9, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 232, 133));

        store.setText("store");
        store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeActionPerformed(evt);
            }
        });
        getContentPane().add(store, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "confidence builder ", "serous practice", " " }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        lt4.setBorder(javax.swing.BorderFactory.createTitledBorder("confidence meter"));
        lt4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "#redo", "0-10 i think so", "10-20", "20-30", "30-40", "40-50 most probabily", "50-60", "60-70", "70-80", "80-90 good chance", "90-100 sure this is it" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lt4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lt4ValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lt4);

        javax.swing.GroupLayout plan1Layout = new javax.swing.GroupLayout(plan1);
        plan1.setLayout(plan1Layout);
        plan1Layout.setHorizontalGroup(
            plan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        plan1Layout.setVerticalGroup(
            plan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(plan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 354, -1, -1));

        tt5.setText("00");
        getContentPane().add(tt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1708, 249, 38, 50));

        tt6.setText("00");
        getContentPane().add(tt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1758, 249, 38, 50));

        tt7.setText("00");
        getContentPane().add(tt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1818, 249, 38, 50));

        jButton3.setText("start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1698, 319, -1, -1));

        jButton4.setText("stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1788, 319, -1, -1));

        jButton5.setText("reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1708, 209, -1, -1));

        jb4.setText("d");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });

        jb2.setText("b");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jb1.setText("a");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb3.setText("c");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1124, 279, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\i1.jpg")); // NOI18N
        jLabel4.setLabelFor(this);
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lt1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lt1ValueChanged
     //if(cb2.getSelectedIndex()==1)

        check.requestFocus();
         //if(lt1.getSelectedIndex()==-1) 
       /* if(cb2.getSelectedIndex()==0)
//check.doClick();
        {jLabel1.setText(lt1.getSelectedValue());try{
        Class.forName("java.sql.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
        Statement s=c.createStatement();String d=null;
       
           d="select rans from "+tf2.getText()+" where question="+cb1.getSelectedItem()+";";
       System.out.println(d);
        ResultSet rs= s.executeQuery(d);
      //  Object p=rs.getObject(0);
                //System.out.println(p);
System.out.println(rs.absolute(1));int i=0;
String ss=rs.getString("rans");
switch (ss.charAt(0)){
case'a': i=0;break;
case 'b':i=1;break;
case'c':i=2;break;
case'd':i=3;break;
}
           
        System.out.println(i);
     int j=lt1.getSelectedIndex();
     //lt1.setSelectedValue(j, rootPaneCheckingEnabled);//Font(font);
     if(j==(i))
     {//next.doClick(2000);
         lt1.setSelectionBackground(Color.GREEN);
            if(cb2.getSelectedIndex()==1)

         jPanel1.setVisible(true);
     d="update "+tf2.getText()+" set attempt=0,ans='"+jLabel1.getText()+"',time1='"+tt4.getText()+"' where question="+cb1.getSelectedItem()+";";
      tfa.setBackground(Color.green);tfa.setText(cb1.getSelectedItem()+" ans ");
     next.doClick();
    
     }//confidece update not applicable for alkane,gr version
     
     else
     {lt1.setSelectionForeground(Color.red);
     lt1.setSelectionBackground(Color.lightGray);
      tfa.setBackground(Color.lightGray);tfa.setText(cb1.getSelectedItem()+" ans ");

     if(cb2.getSelectedIndex()==1)
         jPanel2.setVisible(true);
     d="update "+tf2.getText()+" set attempt=1,ans='"+jLabel1.getText()+"',time1='"+tt4.getText()+"' where question="+cb1.getSelectedItem()+";";
//jTextArea1.requestFocus();
//System.out.println(d+" find error");
//jTextArea1.setWrapStyleWord(true);
     {int arr1[]={i,j};
//lt1.getBackground();

     lt1.setSelectedIndices(arr1);}
                 next.requestFocus();
}
     s.executeUpdate(d);
    }catch(Exception e){System.out.println(e.getMessage());System.out.println( e.getMessage());}
}*/
        // TODO add your handling code here:
    }//GEN-LAST:event_lt1ValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
t1.start();int q=229;
        /*try {
            Class.forName("java.sql.Driver");
         c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
         s=c.createStatement();
       ResultSet rs=  s.executeQuery("select count(*) from "+tf2.getText());
       rs.absolute(1);q=rs.getInt(1);
        } catch (Exception e) {
        }*/
        lt1.requestFocus();        System.out.println("");lt1.setSelectionBackground(Color.blue); 
        cb1.removeAllItems();
        for(int i=1;i<=q;i++)
    cb1.addItem(""+i);t.start();
    jPanel2.setVisible(false);
    jPanel1.setVisible(false);
    if(cb2.getSelectedIndex()==0)
    {plan1.setVisible(false);
    tt4.setVisible(false);tt1.setVisible(false);tt2.setVisible(false);tt3.setVisible(false);tf4.setVisible(false);
tf5.setVisible(false);tf6.setVisible(false);    }

    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
 //if(cb2.getSelectedIndex()==1)
 ans=0;
        store.doClick();
        lt1.setForeground(Color.black);
lt2.setSelectedIndex(0);lt3.setSelectedIndex(1);jPanel2.setVisible(false);jPanel1.setVisible(false);
        jTextArea1.setText("");        t.start();
        tt2.setText(""+00);tt3.setText(""+00);
        //lt1.clearSelection();
        lt1.setSelectedIndex(-1);
        lt1.setSelectionBackground(Color.blue); 
        cb1.setSelectedIndex(cb1.getSelectedIndex()+1);  lt4.setSelectedIndex(5);
        lt1.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
lt1.requestFocus();
try { //NewJFrame ob=new jeemains();
        //ob.con();
        Class.forName("java.sql.Driver");
         c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
         s=c.createStatement();
String d="select ans,text1 from "+tf2.getText()+" where question="+cb1.getSelectedItem()+";";System.out.println(d);
ResultSet rs=s.executeQuery(d); 
rs.absolute(1);
int i=0;

String ss=rs.getString("ans");
        switch (ss.charAt(0)){
case'a': i=0;break;
case 'b':i=1;break;
case'c':i=2;break;
case'd':i=3;break;
default:i=-1;
}//list o=new list(list.get);
        lt1.clearSelection();
        ans=0;lt1.setSelectedIndex(i);   System.out.println(" cb i="+i+"ans="+i);
        
        jTextArea1.setText(rs.getString("text1"));
        } catch (Exception e) {System.out.println( e.getMessage());System.out.println("cb po");
        }       // cb1ItemStateChanged(evt);     // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed


    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed

        t.stop();
       // TODO add your handling code here:
       
       jLabel1.setText(lt1.getSelectedValue());

        try{
        Class.forName("java.sql.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
        Statement s=c.createStatement();String d=null;
       
        if(cb2.getSelectedIndex()==0){ d="select rans from "+tf2.getText()+" where question="+cb1.getSelectedItem()+";";
       System.out.println(d);
        ResultSet rs= s.executeQuery(d);
      //  Object p=rs.getObject(0);
                //System.out.println(p);
System.out.println(rs.absolute(1));int i=0;
String ss=rs.getString("rans");

switch (ss.charAt(0)){
case'a': i=0;break;
case 'b':i=1;break;
case'c':i=2;break;
case'd':i=3;break;
case 'e':i=4;break;
}
           
        System.out.println(i);
     int j=lt1.getSelectedIndex();
     //lt1.setSelectedValue(j, rootPaneCheckingEnabled);//Font(font);
     if(j==(i))
     {//next.doClick(2000);
         lt1.setSelectionBackground(Color.GREEN);
            if(cb2.getSelectedIndex()==1)

         jPanel1.setVisible(true);
            ans=1;
     d="update "+tf2.getText()+" set attempt=0,ans='"+jLabel1.getText()+"',time1='"+tt4.getText()+"' where question="+cb1.getSelectedItem()+";";
//              d="update "+tf2.getText()+" set attempt=0,ans='"+jLabel1.getText()+"',time1='"+tt4.getText()+"' where question="+cb1.getSelectedItem()+";";

     tfa.setBackground(Color.green);tfa.setText(cb1.getSelectedItem()+" ans "+(i+1));
     next.doClick();
     lt1.setSelectedIndex(-1);//lection(-1);
    
     }//confidece update not applicable for alkane,gr version
     
     else
     {lt1.setSelectionForeground(Color.red);
     lt1.setSelectionBackground(Color.lightGray);
      tfa.setBackground(Color.lightGray);tfa.setText(cb1.getSelectedItem()+" ans "+(i+1));
     }
     if(cb2.getSelectedIndex()==1)
         jPanel2.setVisible(true);
     d="update "+tf2.getText()+" set attempt=1,ans='"+jLabel1.getText()+"',time1='"+tt4.getText()+"' where question="+cb1.getSelectedItem()+";";
//jTextArea1.requestFocus();
//System.out.println(d+" find error");
//jTextArea1.setWrapStyleWord(true);
     {int arr1[]={i,j};
//lt1.getBackground();

     lt1.setSelectedIndices(arr1);}
                 next.requestFocus();
                  t.start();ans=5;//tb1.doClick(100);
        tt2.setText(""+00);tt3.setText(""+00);
                      
}
     s.executeUpdate(d);
     c.close();
    }catch(Exception e){System.out.println(e.getMessage());System.out.println( e.getMessage());}

    }//GEN-LAST:event_checkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
lt1.clearSelection();lt1.setSelectionBackground(Color.blue); 
        cb1.setSelectedIndex(cb1.getSelectedIndex()-1);   
        lt1.requestFocus(); ans=9;     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt4ActionPerformed

        t.stop(); 
               tt2.setText(""+00);tt3.setText(""+00);
check.requestFocus();//Focus();
        //tt4.setMultiClickThreshhold(2);// TODO add your handling code here:
    }//GEN-LAST:event_tt4ActionPerformed

    private void tt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tt4MouseExited
t.start();        // TODO add your handling code here:
    }//GEN-LAST:event_tt4MouseExited

    private void cb1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb1PropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cb1PropertyChange

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
//cb1.setForeground(Color.yellow);        // TODO add your handling code here:
         try { //NewJFrame ob=new jeemains();
        //ob.con();
        Class.forName("java.sql.Driver");
         c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
         s=c.createStatement();
String d="select ans,text1,rans from "+tf2.getText()+" where question="+cb1.getSelectedItem()+";";System.out.println(d);
ResultSet rs=s.executeQuery(d); 
rs.absolute(1);
int i=0;


String ss=rs.getString("ans");
        switch (ss.charAt(0)){
case'a': i=0;break;
case 'b':i=1;break;
case'c':i=2;break;
case'd':i=3;break;
case 'e':i=4;break;
default:i=-1;
}//list o=new list(list.get);
       /* if(i>=0){if(rs.getString("rans").equals(rs.getString("ans")))
    lt1.setSelectionBackground(Color.green);//Background(Color.GREEN);
else 
        {lt1.setSelectionBackground(Color.red);lt1.setForeground(Color.white);}}*/
       // if
        lt1.setSelectedIndex(i);   System.out.println(" cb i="+i+"ta = +"+rs.getString("text1"));
        
        jTextArea1.setText(rs.getString("text1"));c.close();
        } catch (Exception e) {System.out.println( e.getMessage());System.out.println("cb po");
        }
    }//GEN-LAST:event_cb1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
lt1.clearSelection();lt1.requestFocus();lt1.setSelectionBackground(Color.blue);

//lt1.setSelectionBackground();
try{
            Class.forName("java.sql.Driver");
           c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
     Statement   st=c.createStatement();//System.out.println(tm.getValueAt(1, 1));
        

         
        String d="update "+tf2.getText()+" set ans=-1 where question="+cb1.getSelectedItem()+";";
    //d="update paper3 set ans=1 where (question=2 and sub=2);";
        //System.out.println(d);
        st.executeUpdate(d);
}        catch(Exception e){System.out.println(e.getMessage());System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lt3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lt3ValueChanged
next.requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_lt3ValueChanged

    private void lt2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lt2ValueChanged
next.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_lt2ValueChanged

    private void lt2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lt2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lt2FocusGained

    private void lt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lt2KeyPressed
//next.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_lt2KeyPressed

    private void databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_databaseActionPerformed

    private void lt4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lt4ValueChanged
check.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_lt4ValueChanged
/*add a timer to abter save so as to 
    see if the person has understood or just skiped*/
    private void storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeActionPerformed
 try{
        Class.forName("java.sql.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
        Statement s=c.createStatement();String d=null;
        if(cb2.getSelectedIndex()==1)     
        d="update "+tf2.getText()+"set confidence='"+lt4.getSelectedValue()+"',text1='"+jTextArea1.getText()+"',reason='"+lt3.getSelectedValuesList()+"' where question="+cb1.getSelectedItem()+";";
     if(Integer.parseInt(tt2.getText())>2 && ans==1) 
        d="update "+tf2.getText()+"set confidence='"+lt4.getSelectedValue()+"',text1='"+jTextArea1.getText()+"',reason='"+lt3.getSelectedValuesList()+":#mpb seen' where question="+cb1.getSelectedItem()+";";
     System.out.println(d);
 s.executeUpdate(d);c.close();
 }catch(Exception e){System.out.println(e.getMessage());System.out.println(e.getMessage());}
               // TODO add your handling code here:
    }//GEN-LAST:event_storeActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
if(cb2.getSelectedIndex()==1)cb2.setEditable(false);
// TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
t2.start();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
t2.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
tt5.setText(00+"");     
tt6.setText(00+"");tt7.setText(00+"");                // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb1KeyPressed
        //keyDown(event, i)        // TODO add your handling code here:
    }//GEN-LAST:event_cb1KeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
lt1.setSelectedIndex(2);   check.doClick();// TODO add your handling code here:
     // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
lt1.setSelectedIndex(0);   
check.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
      lt1.setSelectedIndex(1);   check.doClick();// TODO add your handling code here:
     // TODO add your handling code here:
  // TODO add your handling code here:
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
lt1.setSelectedIndex(3); check.doClick();// TODO add your handling code here:
       // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jb4ActionPerformed
String ans12[]={"","","","",""};String ans1="";String multi;
String multi1[]= new String[4];
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jeemains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jeemains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jeemains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jeemains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jeemains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton check;
    private javax.swing.JTextField database;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JList<String> lt1;
    private javax.swing.JList<String> lt2;
    private javax.swing.JList<String> lt3;
    private javax.swing.JList<String> lt4;
    private javax.swing.JButton next;
    private javax.swing.JPanel plan1;
    private javax.swing.JButton store;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tfa;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField tt2;
    private javax.swing.JTextField tt3;
    private javax.swing.JButton tt4;
    private javax.swing.JTextField tt5;
    private javax.swing.JTextField tt6;
    private javax.swing.JTextField tt7;
    private javax.swing.JTextField ura;
    // End of variables declaration//GEN-END:variables
}