
//import com.mysql.jdbc.Connection;
import java.math.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekhit borole
 */
public class NewJFrame11 extends javax.swing.JFrame {
void ppl(){
   


}
    Connection c=null;
    int i=0;
    Timer t=new Timer((1000),new 
        ActionListener(){public void actionPerformed(ActionEvent e)
{//System.out.println("hello");
    /*int j=0,k=0; i++;
    t3.setText(i+"");if(i==60) 
        t2.setText((Integer.parseInt(t2.getText())));if(j==60)t1.setText(""+k++);if(k==24)k=0;//t1.setText();
*/
    
    int sec=Integer.parseInt(t3.getText());int min=Integer.parseInt(t2.getText()),hour=Integer.parseInt(t1.getText());
    sec++;
    if(sec==6)
    {min++;sec=0;}
if(min==60)
{hour++;min=0;}
if(hour==24)
 hour=0;     

       t1.setText(""+hour);t2.setText(""+min);t3.setText(""+sec);
        //min=179;
           min=179-min;
        sec=60-sec;
tt1.setText(hour+":"+min+":"+sec);

}
        
});
    /**
     * Creates new form NewJFrame11
     */
    public NewJFrame11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lt1 = new javax.swing.JList<>();
        next = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lt2 = new javax.swing.JList<>();
        tt1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tf2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        tb1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tester = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        test = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(1490, 0));
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        t1.setText("00");

        t2.setText("00");

        t3.setText("00");

        cb1.setEditable(true);
        cb1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cb1.setForeground(new java.awt.Color(255, 153, 0));
        cb1.setMaximumRowCount(30);
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        lt1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1     (A)", "2     (B)", "3     (C)", "4     (D)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lt1.setVisibleRowCount(4);
        jScrollPane1.setViewportView(lt1);

        next.setMnemonic('x');
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        save.setMnemonic('s');
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        clear.setMnemonic('c');
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        lt2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "physics", "chemistry", "maths", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lt2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lt2.setSelectedIndex(0);
        lt2.setVisibleRowCount(3);
        lt2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lt2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lt2);

        tt1.setText("00:00:00");
        tt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tt1MouseExited(evt);
            }
        });
        tt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt1ActionPerformed(evt);
            }
        });

        jButton1.setText("check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tf2.setText("paper1");
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "test", "practice" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tb1.setText("restart");
        tb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel1.setText("ur ans");

        jButton3.setText("evaluate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tester.setText("tester");
        tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testerActionPerformed(evt);
            }
        });

        jButton4.setText("mark ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        test.setBackground(new java.awt.Color(255, 204, 0));
        test.setText("test");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton15);
        jToggleButton15.setText("5");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton16);
        jToggleButton16.setText("1");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton17);
        jToggleButton17.setText("2");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton18);
        jToggleButton18.setText("3");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton19);
        jToggleButton19.setText("4");
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton20);
        jToggleButton20.setText("5");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton21);
        jToggleButton21.setText("1");
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton22);
        jToggleButton22.setText("2");
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton23);
        jToggleButton23.setText("3");
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton24);
        jToggleButton24.setText("4");
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton25);
        jToggleButton25.setText("5");
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton26);
        jToggleButton26.setText("1");
        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton27);
        jToggleButton27.setText("2");
        jToggleButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton27ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton28);
        jToggleButton28.setText("3");
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton29);
        jToggleButton29.setText("4");
        jToggleButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton29ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton30);
        jToggleButton30.setText("5");
        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("2");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("3");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("4");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setText("1");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton7);
        jToggleButton7.setText("2");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton8);
        jToggleButton8.setText("3");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setText("4");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setText("5");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton11);
        jToggleButton11.setText("1");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton12);
        jToggleButton12.setText("2");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton13);
        jToggleButton13.setText("3");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton14);
        jToggleButton14.setText("4");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButton21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jToggleButton24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton25))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButton26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton30)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton12)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton16)
                    .addComponent(jToggleButton17)
                    .addComponent(jToggleButton18)
                    .addComponent(jToggleButton19)
                    .addComponent(jToggleButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton21)
                    .addComponent(jToggleButton22)
                    .addComponent(jToggleButton23)
                    .addComponent(jToggleButton24)
                    .addComponent(jToggleButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton26)
                    .addComponent(jToggleButton27)
                    .addComponent(jToggleButton28)
                    .addComponent(jToggleButton29)
                    .addComponent(jToggleButton30))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tt1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(25, 25, 25))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(clear)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(next)
                                .addComponent(save)
                                .addComponent(jButton4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(t1)
                                    .addGap(18, 18, 18)
                                    .addComponent(t2)
                                    .addGap(18, 18, 18)
                                    .addComponent(t3)))
                            .addGap(40, 40, 40))
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tester)
                            .addComponent(test))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt1)
                    .addComponent(tb1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tester)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(test)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1)
                    .addComponent(t2)
                    .addComponent(t3)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(225, 225, 225)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//helper.mains();
private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(29);} 
private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(28);} 
private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(27);} 
private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(26);} 
private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(25);} 
private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(24);} 
private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(23);} 
private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(22);} 
private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(21);} 
private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(20);} 
private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(19);} 
private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(18);} 
private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(17);} 
private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(16);} 
private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(15);} 
private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(14);} 
private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(13);} 
private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(12);} 
private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(11);} 
private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(10);} 
private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(9);} 
private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(8);} 
private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(7);} 
private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(6);} 
private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(5);} 
private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(4);} 
private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(3);} 
private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(2);} 
private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(1);} 
private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(0);} 

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
lt1.clearSelection();
lt1.setSelectionBackground(Color.yellow);
//lt1.setSelectionBackground(Color.getHSBColor(0, 120,215));
lt1.setSelectionForeground(Color.black);
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        
        int a=1+lt1.getSelectedIndex();//actual ans
        if(a==0)
            JOptionPane.showMessageDialog(rootPane, "no option selected");
        else
        {//colar coder
            {int qno=1+cb1.getSelectedIndex();
            switch(qno){
            //helper.mains();
case 30: jToggleButton30.setBackground(Color.green); break;
case 29: jToggleButton29.setBackground(Color.green); break;
case 28: jToggleButton28.setBackground(Color.green); break;
case 27: jToggleButton27.setBackground(Color.green); break;
case 26: jToggleButton26.setBackground(Color.green); break;
case 25: jToggleButton25.setBackground(Color.green); break;
case 24: jToggleButton24.setBackground(Color.green); break;
case 23: jToggleButton23.setBackground(Color.green); break;
case 22: jToggleButton22.setBackground(Color.green); break;
case 21: jToggleButton21.setBackground(Color.green); break;
case 20: jToggleButton20.setBackground(Color.green); break;
case 19: jToggleButton19.setBackground(Color.green); break;
case 18: jToggleButton18.setBackground(Color.green); break;
case 17: jToggleButton17.setBackground(Color.green); break;
case 16: jToggleButton16.setBackground(Color.green); break;
case 15: jToggleButton15.setBackground(Color.green); break;
case 14: jToggleButton14.setBackground(Color.green); break;
case 13: jToggleButton13.setBackground(Color.green); break;
case 12: jToggleButton12.setBackground(Color.green); break;
case 11: jToggleButton11.setBackground(Color.green); break;
case 10: jToggleButton10.setBackground(Color.green); break;
case 9: jToggleButton9.setBackground(Color.green); break;
case 8: jToggleButton8.setBackground(Color.green); break;
case 7: jToggleButton7.setBackground(Color.green); break;
case 6: jToggleButton6.setBackground(Color.green); break;
case 5: jToggleButton5.setBackground(Color.green); break;
case 4: jToggleButton4.setBackground(Color.green); break;
case 3: jToggleButton3.setBackground(Color.green); break;
case 2: jToggleButton2.setBackground(Color.green); break;
case 1: jToggleButton1.setBackground(Color.green); break;

            }
        }
            
int q=1+cb1.getSelectedIndex();//actual q no
       
try{
            Class.forName("java.sql.Driver");
           c=DriverManager.getConnection("jdbc:mysql://localhost:3306/jeemains","root","1234");
     Statement   st=c.createStatement();//System.out.println(tm.getValueAt(1, 1));
        
         //for(int j=0;j<tm.getColumnCount();j++)
        // Object m=tm.getValueAt(i, j);
       //  s="insert into l values("+tm.getValueAt(i,0)+",'"+tm.getValueAt(i,1)+"');";
        String d="update paper3 set ans="+lt1.getSelectedIndex()+" where (question="+cb1.getSelectedItem()+" and sub="+lt2.getSelectedIndex()+");";
    //d="update paper3 set ans=1 where (question=2 and sub=2);";
        System.out.println(d);
        st.executeUpdate(d);
}        catch(Exception e){System.out.println(e.getMessage());}
next.doClick();
clear.doClick();}
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
if(cb1.getSelectedIndex()+1<cb1.getItemCount())
{ int a=1+cb1.getSelectedIndex();
cb1.setSelectedIndex(a);}
lt1.clearSelection();
lt1.setSelectionBackground(Color.YELLOW);
//lt1.setSelectionBackground(Color.getHSBColor(0, 120,215));
lt1.setSelectionForeground(Color.black);
//color
{int a=1+cb1.getSelectedIndex();
switch(a){
case 30: jToggleButton30.setBackground(Color.red); break;
case 29: jToggleButton29.setBackground(Color.red); break;
case 28: jToggleButton28.setBackground(Color.red); break;
case 27: jToggleButton27.setBackground(Color.red); break;
case 26: jToggleButton26.setBackground(Color.red); break;
case 25: jToggleButton25.setBackground(Color.red); break;
case 24: jToggleButton24.setBackground(Color.red); break;
case 23: jToggleButton23.setBackground(Color.red); break;
case 22: jToggleButton22.setBackground(Color.red); break;
case 21: jToggleButton21.setBackground(Color.red); break;
case 20: jToggleButton20.setBackground(Color.red); break;
case 19: jToggleButton19.setBackground(Color.red); break;
case 18: jToggleButton18.setBackground(Color.red); break;
case 17: jToggleButton17.setBackground(Color.red); break;
case 16: jToggleButton16.setBackground(Color.red); break;
case 15: jToggleButton15.setBackground(Color.red); break;
case 14: jToggleButton14.setBackground(Color.red); break;
case 13: jToggleButton13.setBackground(Color.red); break;
case 12: jToggleButton12.setBackground(Color.red); break;
case 11: jToggleButton11.setBackground(Color.red); break;
case 10: jToggleButton10.setBackground(Color.red); break;
case 9: jToggleButton9.setBackground(Color.red); break;
case 8: jToggleButton8.setBackground(Color.red); break;
case 7: jToggleButton7.setBackground(Color.red); break;
case 6: jToggleButton6.setBackground(Color.red); break;
case 5: jToggleButton5.setBackground(Color.red); break;
case 4: jToggleButton4.setBackground(Color.red); break;
case 3: jToggleButton3.setBackground(Color.red); break;
case 2: jToggleButton2.setBackground(Color.red); break;
case 1: jToggleButton1.setBackground(Color.red); break;
}
}
// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
lt1.grabFocus();        // TODO add your handling code here:
        //t.start();
       // if(jComboBox1.getSelectedIndex()==0)
   // jButton1.setVisible(false);
 
jToggleButton30.setText("30");
jToggleButton29.setText("29");
jToggleButton28.setText("28");
jToggleButton27.setText("27");
jToggleButton26.setText("26");
jToggleButton25.setText("25");
jToggleButton24.setText("24");
jToggleButton23.setText("23");
jToggleButton22.setText("22");
jToggleButton21.setText("21");
jToggleButton20.setText("20");
jToggleButton19.setText("19");
jToggleButton18.setText("18");
jToggleButton17.setText("17");
jToggleButton16.setText("16");
jToggleButton15.setText("15");
jToggleButton14.setText("14");
jToggleButton13.setText("13");
jToggleButton12.setText("12");
jToggleButton11.setText("11");
jToggleButton10.setText("10");
jToggleButton9.setText("09");
jToggleButton8.setText("08");
jToggleButton7.setText("07");
jToggleButton6.setText("06");
jToggleButton5.setText("05");
jToggleButton4.setText("04");
jToggleButton3.setText("03");
jToggleButton2.setText("02");
jToggleButton1.setText("01");



    }//GEN-LAST:event_formWindowOpened

    private void tt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt1ActionPerformed
t.stop();
int a=t.hashCode();

        System.out.println(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_tt1ActionPerformed

    private void tt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tt1MouseExited
t.restart();        // TODO add your handling code here:
    }//GEN-LAST:event_tt1MouseExited

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed

        Object s=cb1.getSelectedItem();
lt1.clearSelection();
try{
            Class.forName("java.sql.Driver");
           c=DriverManager.getConnection("jdbc:mysql://localhost:3306/jeemains","root","1234");
     Statement   st=c.createStatement();//System.out.println(tm.getValueAt(1, 1));
        
         //for(int j=0;j<tm.getColumnCount();j++)
        // Object m=tm.getValueAt(i, j);
       //  s="insert into l values("+tm.getValueAt(i,0)+",'"+tm.getValueAt(i,1)+"');";
       String d="select ans from paper3 where (question="+cb1.getSelectedItem()+" and sub="+(lt2.getSelectedIndex())+" ) ;";
    System.out.println(d);
    
       ResultSet rs=st.executeQuery(d);rs.absolute(1);
       
      // System.out.println("hh"+rs);
   // System.out.println(rs.first());
    //System.out.println("ooooooooooooooo"+rs.getObject(1));
int i=rs.getInt(1);System.out.println(i+"val");
lt1.setSelectedIndex(i);
}        
        catch(Exception e){System.out.println(e.getMessage());System.out.println("problem");}

try
{int ss=cb1.getSelectedIndex()+1;
jToggleButton1.setSelected(rootPaneCheckingEnabled);
switch(ss){
    
case 30: jToggleButton30.setSelected(true); break;
case 29: jToggleButton29.setSelected(true); break;
case 28: jToggleButton28.setSelected(true); break;
case 27: jToggleButton27.setSelected(true); break;
case 26: jToggleButton26.setSelected(true); break;
case 25: jToggleButton25.setSelected(true); break;
case 24: jToggleButton24.setSelected(true); break;
case 23: jToggleButton23.setSelected(true); break;
case 22: jToggleButton22.setSelected(true); break;
case 21: jToggleButton21.setSelected(true); break;
case 20: jToggleButton20.setSelected(true); break;
case 19: jToggleButton19.setSelected(true); break;
case 18: jToggleButton18.setSelected(true); break;
case 17: jToggleButton17.setSelected(true); break;
case 16: jToggleButton16.setSelected(true); break;
case 15: jToggleButton15.setSelected(true); break;
case 14: jToggleButton14.setSelected(true); break;
case 13: jToggleButton13.setSelected(true); break;
case 12: jToggleButton12.setSelected(true); break;
case 11: jToggleButton11.setSelected(true); break;
case 10: jToggleButton10.setSelected(true); break;
case 9: jToggleButton9.setSelected(true); break;
case 8: jToggleButton8.setSelected(true); break;
case 7: jToggleButton7.setSelected(true); break;
case 6: jToggleButton6.setSelected(true); break;
case 5: jToggleButton5.setSelected(true); break;
case 4: jToggleButton4.setSelected(true); break;
case 3: jToggleButton3.setSelected(true); break;
case 2: jToggleButton2.setSelected(true); break;
case 1: jToggleButton1.setSelected(true); break;
default:
    System.out.println("problem in switch case of cb1");
}} catch(Exception e){System.out.println(e.getMessage());
//jToggleButton1.setBackground(Color.green);

}
if(lt1.getSelectedIndex()<0){

int a=1+cb1.getSelectedIndex();
switch(a){
case 30: jToggleButton30.setBackground(Color.red); break;
case 29: jToggleButton29.setBackground(Color.red); break;
case 28: jToggleButton28.setBackground(Color.red); break;
case 27: jToggleButton27.setBackground(Color.red); break;
case 26: jToggleButton26.setBackground(Color.red); break;
case 25: jToggleButton25.setBackground(Color.red); break;
case 24: jToggleButton24.setBackground(Color.red); break;
case 23: jToggleButton23.setBackground(Color.red); break;
case 22: jToggleButton22.setBackground(Color.red); break;
case 21: jToggleButton21.setBackground(Color.red); break;
case 20: jToggleButton20.setBackground(Color.red); break;
case 19: jToggleButton19.setBackground(Color.red); break;
case 18: jToggleButton18.setBackground(Color.red); break;
case 17: jToggleButton17.setBackground(Color.red); break;
case 16: jToggleButton16.setBackground(Color.red); break;
case 15: jToggleButton15.setBackground(Color.red); break;
case 14: jToggleButton14.setBackground(Color.red); break;
case 13: jToggleButton13.setBackground(Color.red); break;
case 12: jToggleButton12.setBackground(Color.red); break;
case 11: jToggleButton11.setBackground(Color.red); break;
case 10: jToggleButton10.setBackground(Color.red); break;
case 9: jToggleButton9.setBackground(Color.red); break;
case 8: jToggleButton8.setBackground(Color.red); break;
case 7: jToggleButton7.setBackground(Color.red); break;
case 6: jToggleButton6.setBackground(Color.red); break;
case 5: jToggleButton5.setBackground(Color.red); break;
case 4: jToggleButton4.setBackground(Color.red); break;
case 3: jToggleButton3.setBackground(Color.red); break;
case 2: jToggleButton2.setBackground(Color.red); break;
case 1: jToggleButton1.setBackground(Color.red); break;
}}
//cb1.setFont(font);      // TODO add youhandling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jLabel1.setText(lt1.getSelectedValue());

        try{
        Class.forName("java.sql.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/jeemains","root","1234");
        Statement s=c.createStatement();
        String d="select rans from "+tf2.getText()+" where (question="+cb1.getSelectedItem()+" and sub="+lt2.getSelectedIndex()+");";
        System.out.println(d);
        ResultSet rs= s.executeQuery(d);
      //  Object p=rs.getObject(0);
                //System.out.println(p);
System.out.println(rs.absolute(1));
     int i=rs.getInt(1);
        System.out.println(i);
     int j=lt1.getSelectedIndex();
     //lt1.setSelectedValue(j, rootPaneCheckingEnabled);//Font(font);
     if(j==i)
       lt1.setSelectionBackground(Color.GREEN);
     
     else
     {lt1.setSelectionForeground(Color.red);
     lt1.setSelectionBackground(Color.lightGray);
     {int arr1[]={i,j};
//lt1.getBackground();
     lt1.setSelectedIndices(arr1);}}
    }catch(Exception e){System.out.println(e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
    }//GEN-LAST:event_tf2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
          System.out.println(tb1.isSelected());// TODO add your handling code here:
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void tb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb1ActionPerformed
        t.restart(); 
       // System.out.println(tb1.isSelected());// TODO add your handling code here:
    }//GEN-LAST:event_tb1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int score=0;
        try{
    String d1="",d2="",d3="";
    Class.forName("java.sql.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/jeemains","root","1234");
        Statement st=c.createStatement();
    {for(int i=1;i<=(cb1.getItemCount());i++)
        for(int j=0;j<3;j++)
        { d1="select ans,rans from "+tf2.getText()+" where(question="+i+" and sub="+j+");";
            System.out.println(d1);
                
        ResultSet rs1=st.executeQuery(d1);
    //ResultSet rs2=st.executeQuery("select rans from "+tf2.getText()+" where(question="+i+" and sub="+j+");");
    //rs1.absolute(1);//rs2.absolute(1);
    rs1.first();
    if(rs1.getInt("ans")==rs1.getInt("rans"))
    {d2="Update "+tf2.getText()+" set checker=4 where (question="+i+" and sub="+j+");";
        System.out.println(d2);    
    st.executeUpdate(d2);
    score+=4;
    }
    else if(rs1.getInt("ans")!=-1)
    {score-=1;
    d3="Update "+tf2.getText()+" set checker=-1 where (question="+i+" and sub="+j+");";
    st.executeUpdate(d3);   
    System.out.println(d3);
    }
        }
    JOptionPane.showMessageDialog(null, score);}
}   catch(Exception e){System.out.println(e.getMessage());}     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testerActionPerformed
Color cc=Color.pink;
tester.setBackground(cc);
        System.out.println(tb1.isSelected());        // TODO add your handling code here:
    }//GEN-LAST:event_testerActionPerformed

    /*
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
     NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(0);     // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(1);          // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(2);          // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
NewJFrame11 ob=new NewJFrame11();ob.ppl();cb1.setSelectedIndex(3);          // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton27ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton29ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton30ActionPerformed
**/
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int a=1+cb1.getSelectedIndex();
        if(lt1.getSelectedIndex()>-1)
        {
       // jToggleButton1.setBackground(Color.orange);
        switch(a){
        
case 30: jToggleButton30.setBackground(Color.orange); break;
case 29: jToggleButton29.setBackground(Color.orange); break;
case 28: jToggleButton28.setBackground(Color.orange); break;
case 27: jToggleButton27.setBackground(Color.orange); break;
case 26: jToggleButton26.setBackground(Color.orange); break;
case 25: jToggleButton25.setBackground(Color.orange); break;
case 24: jToggleButton24.setBackground(Color.orange); break;
case 23: jToggleButton23.setBackground(Color.orange); break;
case 22: jToggleButton22.setBackground(Color.orange); break;
case 21: jToggleButton21.setBackground(Color.orange); break;
case 20: jToggleButton20.setBackground(Color.orange); break;
case 19: jToggleButton19.setBackground(Color.orange); break;
case 18: jToggleButton18.setBackground(Color.orange); break;
case 17: jToggleButton17.setBackground(Color.orange); break;
case 16: jToggleButton16.setBackground(Color.orange); break;
case 15: jToggleButton15.setBackground(Color.orange); break;
case 14: jToggleButton14.setBackground(Color.orange); break;
case 13: jToggleButton13.setBackground(Color.orange); break;
case 12: jToggleButton12.setBackground(Color.orange); break;
case 11: jToggleButton11.setBackground(Color.orange); break;
case 10: jToggleButton10.setBackground(Color.orange); break;
case 9: jToggleButton9.setBackground(Color.orange); break;
case 8: jToggleButton8.setBackground(Color.orange); break;
case 7: jToggleButton7.setBackground(Color.orange); break;
case 6: jToggleButton6.setBackground(Color.orange); break;
case 5: jToggleButton5.setBackground(Color.orange); break;
case 4: jToggleButton4.setBackground(Color.orange); break;
case 3: jToggleButton3.setBackground(Color.orange); break;
case 2: jToggleButton2.setBackground(Color.orange); break;
case 1: jToggleButton1.setBackground(Color.orange); break;
}
        
        }else
            switch(a)
            {
case 30: jToggleButton30.setBackground(Color.pink); break;
case 29: jToggleButton29.setBackground(Color.pink); break;
case 28: jToggleButton28.setBackground(Color.pink); break;
case 27: jToggleButton27.setBackground(Color.pink); break;
case 26: jToggleButton26.setBackground(Color.pink); break;
case 25: jToggleButton25.setBackground(Color.pink); break;
case 24: jToggleButton24.setBackground(Color.pink); break;
case 23: jToggleButton23.setBackground(Color.pink); break;
case 22: jToggleButton22.setBackground(Color.pink); break;
case 21: jToggleButton21.setBackground(Color.pink); break;
case 20: jToggleButton20.setBackground(Color.pink); break;
case 19: jToggleButton19.setBackground(Color.pink); break;
case 18: jToggleButton18.setBackground(Color.pink); break;
case 17: jToggleButton17.setBackground(Color.pink); break;
case 16: jToggleButton16.setBackground(Color.pink); break;
case 15: jToggleButton15.setBackground(Color.pink); break;
case 14: jToggleButton14.setBackground(Color.pink); break;
case 13: jToggleButton13.setBackground(Color.pink); break;
case 12: jToggleButton12.setBackground(Color.pink); break;
case 11: jToggleButton11.setBackground(Color.pink); break;
case 10: jToggleButton10.setBackground(Color.pink); break;
case 9: jToggleButton9.setBackground(Color.pink); break;
case 8: jToggleButton8.setBackground(Color.pink); break;
case 7: jToggleButton7.setBackground(Color.pink); break;
case 6: jToggleButton6.setBackground(Color.pink); break;
case 5: jToggleButton5.setBackground(Color.pink); break;
case 4: jToggleButton4.setBackground(Color.pink); break;
case 3: jToggleButton3.setBackground(Color.pink); break;
case 2: jToggleButton2.setBackground(Color.pink); break;
case 1: jToggleButton1.setBackground(Color.pink); break;
}
      next.doClick();
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lt2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lt2ValueChanged
tester.setText(""+lt2.getSelectedIndex());  NewJFrame11 ob=new NewJFrame11();
// TODO add your handling code here:
    }//GEN-LAST:event_lt2ValueChanged
void color(Color cc){test.setBackground(cc);}
    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        // TODO add your handling code here:
        NewJFrame11 ob=new NewJFrame11();
        String s="Color.blue";
        float a=0;
        float b=255, c=0;
       //Color cc= Color.HSBtoRGB(a, b, c);Color.HSBtoRGB(c, c, c)
        Color cp=Color.getColor("Color.blue");System.out.println(Color.green);
        //Color cc=Color.pink;
test.setBackground(cp);
tester.setBackground(new java.awt.Color(a=0,c=255,b=0));

      //  System.out.println(tb1.isSelected()); 
    }//GEN-LAST:event_testActionPerformed
//int c=0;    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JList<String> lt1;
    private javax.swing.JList<String> lt2;
    private javax.swing.JButton next;
    private javax.swing.JButton save;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JToggleButton tb1;
    private javax.swing.JToggleButton test;
    private javax.swing.JButton tester;
    private javax.swing.JTextField tf2;
    private javax.swing.JButton tt1;
    // End of variables declaration//GEN-END:variables
} 
