
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.sun.javafx.scene.text.TextLayout;
/**
 *
 * @author lekhit borole
 */import java.sql.DriverManager;
import java.sql.ResultSet;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.ListModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import javax.swing.Timer;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class test1 extends javax.swing.JFrame {

       
   Timer t=new Timer((1000),new 
        ActionListener(){public void actionPerformed(ActionEvent e)
{ int sec,min,hour;
    String[] s=(time.getText()).split(":");
    
    min=Integer.parseInt(s[1]);
        hour=Integer.parseInt(s[0]);


    sec=Integer.parseInt(s[2]);
    //sec=
    
if(min==00)
{hour--;min=60;}
if(sec==00)
    {min--;sec=60;}
if(hour==0)
{//t.stop();   // JOptionPane.showMessageDialog(rootPane, "times up....");
}
    sec--;

       //t7.setText(""+hour);t5.setText(""+min);t4.setText(""+sec);
        //min=179;
       // if(sec==00)
           //min=179-min;
        //sec=60-sec;
time.setText(hour+":"+min+":"+sec);
//if()

}});
    /**
     * Creates new form test1
     */
    public test1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        next = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rans1 = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox<>();
        time = new javax.swing.JToggleButton();
        cb2 = new javax.swing.JComboBox<>();
        database = new javax.swing.JTextField();
        ura = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtp = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jb4 = new javax.swing.JToggleButton();
        jb3 = new javax.swing.JToggleButton();
        jb2 = new javax.swing.JToggleButton();
        jb1 = new javax.swing.JToggleButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        commit = new javax.swing.JButton();
        single = new javax.swing.JRadioButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jb14 = new javax.swing.JButton();
        jb12 = new javax.swing.JButton();
        jb11 = new javax.swing.JButton();
        jb13 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        tableplane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        te1 = new javax.swing.JTextField();
        te2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        total_question = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("new");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setMnemonic('b');
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 109, 103));

        clear.setText("clear ");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 109, 101));

        next.setMnemonic('n');
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel3.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 109, 100));

        save.setMnemonic('s');
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 109, 92));

        jLabel6.setText("lekhit");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -60, 400, 830));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 140, 600));

        rans1.setText("rans");
        getContentPane().add(rans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 82, -1));

        cb1.setBackground(new java.awt.Color(0, 255, 51));
        cb1.setEditable(true);
        cb1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 120, 86));

        time.setText("01:00:00");
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "warn", "practice", "test" }));
        cb2.setSelectedIndex(2);
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));

        database.setText("jeeadv");
        database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseActionPerformed(evt);
            }
        });
        getContentPane().add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 80, -1));

        ura.setText("ur ans:-");
        ura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uraActionPerformed(evt);
            }
        });
        getContentPane().add(ura, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, 100, 30));

        tf2.setText("crt1apaper1");
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 80, -1));

        jComboBox1.setMaximumRowCount(10);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 90, -1));

        jtp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        jLabel1.setText("ans here:-");

        jCheckBox9.setText("intelligent input");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox9)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jCheckBox9)
                .addContainerGap(1660, Short.MAX_VALUE))
        );

        jtp.addTab("input", jPanel2);

        jb4.setText("d");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });

        jb3.setText("c");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jb2.setText("b");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jb1.setText("a");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("matrix");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        commit.setText("commit");
        commit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitActionPerformed(evt);
            }
        });

        single.setText("single");
        single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleActionPerformed(evt);
            }
        });

        jCheckBox5.setText("c");

        jCheckBox6.setText("d");

        jCheckBox7.setText("a");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("b");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(single))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(3, 3, 3)
                        .addComponent(commit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(single)
                .addGap(30, 30, 30)
                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(commit))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox5)
                        .addComponent(jCheckBox8)
                        .addComponent(jCheckBox6))))
        );

        jtp.addTab("multiple", jPanel1);

        jb14.setText("d");
        jb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb14ActionPerformed(evt);
            }
        });

        jb12.setText("b");
        jb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb12ActionPerformed(evt);
            }
        });

        jb11.setText("a");
        jb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb11ActionPerformed(evt);
            }
        });

        jb13.setText("c");
        jb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jb11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jb12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jb13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jb14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("a");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("c");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("d");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("b");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("a");

        jCheckBox2.setText("b");

        jCheckBox3.setText("c");

        jCheckBox4.setText("d");

        jButton6.setMnemonic('c');
        jButton6.setText("next1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jCheckBox2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox4))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jRadioButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)))))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addGap(681, 681, 681)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(536, Short.MAX_VALUE))
        );

        jtp.addTab("single", jPanel4);

        getContentPane().add(jtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 170, -1));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "question", "rans", "ans", "evaluate", "Title 5"
            }
        ));
        tb1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tb1);

        jLabel3.setText("SET VALUES");

        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton1.setText("get");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("column");

        jButton2.setText("save1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("row");

        jButton4.setText("evaluate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("clean");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tableplaneLayout = new javax.swing.GroupLayout(tableplane);
        tableplane.setLayout(tableplaneLayout);
        tableplaneLayout.setHorizontalGroup(
            tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableplaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableplaneLayout.createSequentialGroup()
                .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(126, 126, 126)
                .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableplaneLayout.createSequentialGroup()
                        .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tableplaneLayout.createSequentialGroup()
                                .addComponent(te1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableplaneLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)))
                        .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tableplaneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel3))
                            .addGroup(tableplaneLayout.createSequentialGroup()
                                .addComponent(te2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tableplaneLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(update)))))
        );
        tableplaneLayout.setVerticalGroup(
            tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableplaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(te1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(te2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGroup(tableplaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableplaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(update))
                    .addGroup(tableplaneLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))))
        );

        getContentPane().add(tableplane, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 530, 630));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, -1, -1));

        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\lekhit borole\\Documents\\manas iit\\013.png")); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setAutoscrolls(true);
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 570));

        total_question.setText("40");
        total_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_questionActionPerformed(evt);
            }
        });
        getContentPane().add(total_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 50, -1));

        jLabel5.setText("total question");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton7.setText("jButton7");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear.doClick();test ob=new test();

        cb1.setSelectedIndex(cb1.getSelectedIndex()-1);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        //test ob=new test();
/*jRadioButton2.setSelected(false);
        jRadioButton5.setSelected(false);
jRadioButton3.setSelected(false);jRadioButton4.setSelected(false);
*/
buttonGroup2.clearSelection();
        jb1.setSelected(false);
        jb2.setSelected(false);
        jb3.setSelected(false);
        jb4.setSelected(false);
        input.setText("");
        //check.setText("checker");
        for(int i=1;i<5;i++)
        ans[i]="";
        ans1="";
        //feature changed ura.setText(""+cb1.getSelectedItem()+":-"+ans1);
        ura.setText("");
        test ob=new test();
               DefaultTableModel tm=(DefaultTableModel)tb1.getModel(); 

        if(clear.hasFocus())//System.out.println("clear has focus");
tm.setValueAt("", cb1.getSelectedIndex(), 2);
        rans1.setVisible(false);

    }//GEN-LAST:event_clearActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        //t.start();
        clear.doClick();test ob=new test();
        // rs=ob.conn(database.getText(),tf2.getText(), "select", "rans", "question="+cb1.getSelectedItem());
        //ob.conn(database.getText(),tf2.getText(), "update  ", "reason='correction time="+tt1.getText()+"'", "question="+cb1.getSelectedItem());

        try {
            //c.close();
        } catch (Exception e) {
        }
        cb1.setSelectedIndex(cb1.getSelectedIndex()+1);        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        setTitle("edited");
        //jTextArea1.append("\n$"+cb1.getSelectedItem()+":-"+ans1);    
       DefaultTableModel tm=(DefaultTableModel)tb1.getModel(); 
        //rans1.setText(ans1);
        
        test1 ob=new test1();
          //rans1.setText(""+ tm.getValueAt( cb1.getSelectedIndex(), 1));  
       try {//ob.conn();
           tm.setValueAt(ans1, cb1.getSelectedIndex(), 2);
            //s.executeUpdate(d);
//ob.save(cb1.getSelectedIndex()+1, ans1);
            System.out.println(ans1+"urnas+save has ans="+ tm.getValueAt( cb1.getSelectedIndex(), 1));
            switch(cb2.getSelectedIndex())
            {case 1:
                if(ans1.equalsIgnoreCase(""+ tm.getValueAt( cb1.getSelectedIndex(), 1)))
                {ura.setBackground(Color.green);next.doClick();}
                else {
                    next.requestFocus();
                    rans1.setText(""+tm.getValueAt(cb1.getSelectedIndex(), 1));
                    ura.setBackground(Color.lightGray);
                    rans1.setVisible(true);
                    //rans1.setText(rs.getString("rans"));
                }
                break;
                case 0:
                if(ans1.equalsIgnoreCase(""+ tm.getValueAt( cb1.getSelectedIndex(), 1))==false)
                {ura.setBackground(Color.lightGray);                                 rans1.setText(""+tm.getValueAt(cb1.getSelectedIndex(), 1));
            rans1.setVisible(true);
           next.requestFocus();

                }else
                {   next.doClick();
                ura.setBackground(Color.white); 
                } break;
                case 2:                next.doClick();System.out.println("unreachanble in cb2");
                break;
            }}catch(Exception e){System.out.println("save error "+e.getMessage());
            //ob.update(ans1,tf2.getText(),cb1.getSelectedItem());
            //c.close();} catch (Exception e){System.out.println(e.getMessage()+"save exception");
            //ob.conn(ans1, ans1, ans1, ans1, ans1);
        }//next.doClick();
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        test ob=new test();String ss="";
        int i=cb1.getSelectedIndex();
        String s="C:\\Users\\lekhit borole\\Documents\\manas iit\\01"+i+".png";
        jLabel7.setIcon(new javax.swing.ImageIcon(s)); // NOI18N
        try {
            DefaultTableModel tm=(DefaultTableModel)tb1.getModel();       
            String ssp=""+ tm.getValueAt( cb1.getSelectedIndex(), 2);ssp=ssp.toLowerCase();
            
            System.out.println("cb="+ssp);
            int l=ssp.length();
            if(l>0)
            {clear.doClick();
                ura.setText(ssp);ans1=ssp;do{switch(ssp.charAt(l-1)){case 'a':jb1.setSelected(true); ans[1]="a";break;
                    case 'b':jb2.setSelected(true);ans[2]="b";break;
                    case 'c':jb3.setSelected(true);ans[3]="c";break;
                    case 'd':jb4.setSelected(true);ans[4]="d";break;
                    //default: ura.setText("");
                }if(jtp.getSelectedIndex()==1)
                input.setText(ans1);
                l--;}while(l>0);

        } }catch (Exception e){System.out.println("cb po"+e.getMessage());
        }
        //jtp.setSelectedIndex(ob.qtype(tf2.getText(),cb1.getSelectedItem()));

        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        jb1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
if(time.isSelected()==false)t.start();
else 
    t.stop();
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed

        //        System.out.println(cb2.getSelectedIndex());        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseActionPerformed
jComboBox1.requestFocus();        // TODO add your handling code here:
        test ob= new test();
        jComboBox1.removeAllItems();
        ResultSet rs=ob.conn(database.getText(),"show tables;");
        //jComboBox1.insertItemAt("ioioioio",0);

        try {
            System.out.println( rs.getString(1));
            do
            {
                jComboBox1.addItem(rs.getString(1));
                //System.out.println(rs.getString(1)+"this part");
            }while(rs.next());
            //jComboBox1.addItem(ans1);
        } catch (Exception e) {System.out.println(e.getMessage());
        }        jComboBox1.requestFocus();        // TODO add your handling code here:
        
        
        jComboBox1.addItem("NEW");
    }//GEN-LAST:event_databaseActionPerformed

    private void uraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uraActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        test ob= new test();
        jComboBox1.removeAllItems();
        ResultSet rs=ob.conn(database.getText(),"show tables;");

        try {//rs.absolute(1);
            rs.first();
            System.out.println( rs.getString(1));
            while(rs.next())
            {jComboBox1.addItem(rs.getString(1));//System.out.println(rs.getString(1)+"this part");
            }
            //jComboBox1.addItem(ans1);
        } catch (Exception e) {System.out.println(e.getMessage());
        }
        jComboBox1.addItem("NEW");
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         tf2.setText(jComboBox1.getSelectedItem()+"");
         //tf2.action(Act, evt)
       
tb1.getSelectedRows();

        // tf2.setText(""+jComboBox1.getSelectedItem());
        //ob.conn(database.getText(),""+ jComboBox1.getSelectedItem(), "select", "");// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
 String ans[]={"","","","",""};String ans1="";

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
 DefaultTableModel tm=(DefaultTableModel)tb1.getModel();       
 //tm.getValueAt(WIDTH, WIDTH)
tm.setRowCount(0);System.out.println(tf2.getText().substring(3));
 //tm.setValueAt(tm, WIDTH, WIDTH);
try {
             if(tf2.getText().substring(0, 3).equals("NEW"))      
 {   //tm.addColumn("question", ["",""]);
  //for(int i=0;i<;i++)
       //tm.addRow();]
       //tm.setRowCount(20);
       tm.setRowCount(Integer.parseInt(tf2.getText().substring(3)));
     for (int i = 1; i <= Integer.parseInt(tf2.getText().substring(3)); i++) {
         
     
       tm.setValueAt(i,i-1, 0);}
 }
        } catch (Exception e) {
        }
 try {
             Class.forName("java.sql.Driver");
         Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
          Statement s=c.createStatement();
         ResultSet rs=s.executeQuery("select count(*) from "+tf2.getText()+";");rs.absolute(1);
         int qni=rs.getInt(1);
         rs.absolute(1);
          //while(rs.getInt(1
          for(int i=1;i<=qni;i++)
            {rs=s.executeQuery("select ans,rans,question from "+tf2.getText()+" where question="+i+";");
            rs.first();
            String ans=rs.getString("ans");
                String rans=rs.getString("rans");  String question=rs.getString("question");
                if(ans.equals("-1"))   
                    ans="";
                Object arr[]={question,rans,ans};
                    System.out.println("pass");
                    tm.addRow(arr);
            cb1.addItem(""+i);
            }
       c.close(); } catch (Exception e) {System.out.println(e.getMessage());
        }        
            //c.close();} catch (Exception e){System.out.println(e.getMessage());qni=250;
       // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        //ans+="d";        // TODO add your handling code here:
        if(jb4.isSelected())      ans[4]="d";
        else if(jb4.isSelected()==false) ans[4]="";
        ans1="";for(int i=1;i<5;i++)
        ans1+=(ans[i]);ura.setText("");ura.setText(""+cb1.getSelectedItem()+":-"+ans1);
        if(single.isSelected()&&cb2.getSelectedIndex()!=2&&(jb4.isSelected()))     save.doClick();

        //if(jRadioButton2.isSelected()&&cb2.getSelectedIndex()!=2)next.doClick();
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        //ans+="c";        // TODO add your handling code here:
        if(jb3.isSelected())      ans[3]="c";
        else if(jb3.isSelected()==false) ans[3]="";
        ans1="";for(int i=1;i<5;i++)
        ans1+=(ans[i]);ura.setText("");ura.setText(""+cb1.getSelectedItem()+":-"+ans1);
        if(single.isSelected()&&cb2.getSelectedIndex()!=2&&(jb3.isSelected()))     save.doClick();
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        //ans+="b"; // TODO add your handling code here:
        if(jb2.isSelected())      ans[2]="b";
        else if(jb2.isSelected()==false) ans[2]="";
        ans1="";for(int i=1;i<5;i++)
        ans1+=(ans[i]);ura.setText("");ura.setText(""+cb1.getSelectedItem()+":-"+ans1);
        if(single.isSelected()&&cb2.getSelectedIndex()!=2&&(jb2.isSelected()))     save.doClick();

        //if(jRadioButton2.isSelected()&&cb2.getSelectedIndex()!=2)save.doClick();
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        if(jb1.isSelected())      ans[1]="a";
        else if(jb1.isSelected()==false) ans[1]="";
        ans1="";for(int i=1;i<5;i++)
        ans1+=(ans[i]);ura.setText(""+cb1.getSelectedItem()+":-"+ans1);
        if(single.isSelected()&&cb2.getSelectedIndex()!=2&&(jb3.isSelected()))     save.doClick();

        //if(jRadioButton2.isSelected()&&cb2.getSelectedIndex()!=2)save.doClick();

        // TODO add your handling code here:
    }//GEN-LAST:event_jb1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){
            commit.setVisible(true); }
        else {       // TODO add your handling code here:
            commit.setVisible(false);}

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void commitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitActionPerformed
      
    }//GEN-LAST:event_commitActionPerformed

    private void singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleActionPerformed
if(single.isSelected())
{ buttonGroup1.add(jb2); buttonGroup1.add(jb1);buttonGroup1.add(jb3);    
buttonGroup1.add(jb4);}
else
    try {
        buttonGroup1.remove(jb1);buttonGroup1.remove(jb2);buttonGroup1.remove(jb3);buttonGroup1.remove(jb4);
    } catch (Exception e) {
    }
// TODO add your handling code here:
    }//GEN-LAST:event_singleActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        ans1=input.getText();// TODO add your handling code here:
if(jCheckBox9.isSelected())
{ int i=Integer.parseInt(ans1);
    switch(i){
        case 1:ans1="a";break;
        case 2:ans1="b";break;
        case 3:ans1="c";break;
        case 4:ans1="d";break;
        
    }}
    ura.setText(""+cb1.getSelectedItem()+":-"+ans1);   save.doClick();
    }//GEN-LAST:event_inputActionPerformed

    private void jb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb14ActionPerformed
        ans1="d"; ura.setText(""+cb1.getSelectedItem()+":-"+ans1); save.doClick();// TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jb14ActionPerformed

    private void jb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb12ActionPerformed
        ans1="b";     ura.setText(""+cb1.getSelectedItem()+":-"+ans1);     save.doClick();// TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jb12ActionPerformed

    private void jb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb11ActionPerformed
        ans1="a";           ura.setText(""+cb1.getSelectedItem()+":-"+ans1);   save.doClick();// TODO add your handling code here:
    }//GEN-LAST:event_jb11ActionPerformed

    private void jb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb13ActionPerformed
        ans1="c";      ura.setText(""+cb1.getSelectedItem()+":-"+ans1);     save.doClick();// TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jb13ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        int  totalquestion =Integer.getInteger(total_question.getText());
        for (int i=1;i<totalquestion;i++)
            cb1.addItem(""+i);
        
        tableplane.setVisible(false);
                    test ob= new test();
        jComboBox2.removeAllItems();
     
        ResultSet   rs=ob.conn("jeeadv","show databases;"),rs1;
        //jComboBox1.insertItemAt("ioioioio",0);
       // rs.absolute();

        try {      
             //rs1=ob.conn(database.getText(), "select now();");
            //rs1.absolute(1);
                  //  setTitle(rs.getString(1));
                   // rs=ob.conn("jeeadv","show databases;");
            rs.absolute(1);
                    //setTitle(ob.conn(database.getText(), "select now();").getString(1));

            System.out.println( rs.getString(1));
            do
            {
                jComboBox2.addItem(rs.getString(1));
                //System.out.println(rs.getString(1)+"this part");
            }while(rs.next());
            //jComboBox1.addItem(ans1);
        } catch (Exception e) {System.out.println(e.getMessage());
        } 
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
String getter(int question,int what_1_rans_2_ans){String get=null;
int i=question;int i1=2;//=Integer.parseInt(te2.getText());

switch(what_1_rans_2_ans){
    case 1:i1=1;break;
    
    case 2:i1=2;break;}
 DefaultTableModel tm=(DefaultTableModel)tb1.getModel();    
get=""+tm.getValueAt(i-1, i1-1);
return(get);}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int i=Integer.parseInt(te1.getText());
int i1=Integer.parseInt(te2.getText());
 DefaultTableModel tm=(DefaultTableModel)tb1.getModel();    
 //ValueAt(jTextField1.getText(), i-1, i1-1);
System.out.println(tm.getValueAt(i-1, i1-1));
//test1 ob=new test1();
//ob.save(i,jTextField1.getText() );

//
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
void save(int question,String ans){
int i=question;
        int i1=3;//anser column
 DefaultTableModel tm=(DefaultTableModel)tb1.getModel();    
 tm.setValueAt(ans, i, i1);
 }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     //   Object o=tm.getValueAt(i, i1);System.out.println(o);
int i=Integer.parseInt(te1.getText());
int i1=Integer.parseInt(te2.getText());
 DefaultTableModel tm=(DefaultTableModel)tb1.getModel();    
 tm.setValueAt(jTextField1.getText(), i-1, i1-1);
 //test1 ob=new test1();
        //System.out.println(tm.getValueAt(i-1, i1-1));

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

 DefaultTableModel tm=(DefaultTableModel)tb1.getModel();    
//ob.conn(database.getText(), "insert into "+tf2.getText()+" (question");
try {
             Class.forName("java.sql.Driver");
         Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database.getText(),"root","1234");
          Statement s=c.createStatement();
         ResultSet rs=s.executeQuery("select count(*) from "+tf2.getText()+";");rs.absolute(1);
         int qni=rs.getInt(1);
         rs.absolute(1);
          //while(rs.getInt(1
          for(int i=1;i<=qni;i++)
            {System.out.println("update "+tf2.getText()+" set ans='"+tm.getValueAt(i-1, 2)+"' where question="+tm.getValueAt(i-1, 0)+";");
                s.executeUpdate("update "+tf2.getText()+" set ans='"+tm.getValueAt(i-1, 2)+"' where question="+tm.getValueAt(i-1, 0)+";");}
rs=s.executeQuery("select now();");rs.absolute(1);
          setTitle("updated_"+rs.getString(1));
       
} catch (Exception e) {System.out.println(e.getMessage()+"error");
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
      //  jb1.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
if(jToggleButton1.isSelected())
        tableplane.setVisible(true);   
else
        tableplane.setVisible(false);   
// TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=9;System.out.println(getTitle().equals(getTitle()));
        if(getTitle().equals("edited"))
        { i=JOptionPane.showConfirmDialog(rootPane, "like to update","confirm",1)   ; 
if(i==0)
{ update.doClick();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
}
else if(i==2)
setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
else setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
}
      //String s=  getTitle();
        System.out.println("root pane="+i);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 DefaultTableModel tm=(DefaultTableModel)tb1.getModel();    
for(int i=0;i<tm.getRowCount();i++)
{ if((""+tm.getValueAt(i, 1)).equalsIgnoreCase(""+tm.getValueAt(i, 2)))
tm.setValueAt("correct", i, 3);
    else if(tm.getValueAt(i, 2).equals(""))
        tm.setValueAt("", i, 3);
    else 
        tm.setValueAt("wrong", i, 3);
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
next.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel tm=(DefaultTableModel)tb1.getModel();    
//JOptionPane.showConfirmDialog(rootPane, "this cannot be undone");
        tm.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
database.setText(jComboBox2.getSelectedItem()+"");        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
jb11.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
jb12.doClick();          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
jb13.doClick();          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
jb14.doClick();  //System.out.println(TextLayout.TYPE_UNDERLINEALIGN_LEFT);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
//if(jCheckBox8.isSelected())jb2.doClick(); else if(jCheckBox7.isSelected()==false)
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
//if(jCheckBox8.isSelected())jb2.doClick(); 
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
next.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed


// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton clear;
    private javax.swing.JButton commit;
    private javax.swing.JTextField database;
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jb1;
    private javax.swing.JButton jb11;
    private javax.swing.JButton jb12;
    private javax.swing.JButton jb13;
    private javax.swing.JButton jb14;
    private javax.swing.JToggleButton jb2;
    private javax.swing.JToggleButton jb3;
    private javax.swing.JToggleButton jb4;
    private javax.swing.JTabbedPane jtp;
    private javax.swing.JButton next;
    private javax.swing.JTextField rans1;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton single;
    private javax.swing.JPanel tableplane;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField te1;
    private javax.swing.JTextField te2;
    private javax.swing.JTextField tf2;
    private javax.swing.JToggleButton time;
    private javax.swing.JTextField total_question;
    private javax.swing.JButton update;
    private javax.swing.JTextField ura;
    // End of variables declaration//GEN-END:variables
}
